FROM ubuntu AS build
RUN apt-get update -y
RUN apt-get install maven -y && apt-get install git -y
RUN git clone https://github.com/shashirajraja/onlinebookstore.git

WORKDIR /onlinebookstore/
RUN mvn clean package

FROM alpine
RUN apk add openjdk8
ADD https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.100/bin/apache-tomcat-8.5.100.tar.gz tomcat.tar.gz
RUN tar -xvf tomcat.tar.gz -C /opt/
COPY --from=build /onlinebookstore/target/**.war /opt/apache-tomcat-8.5.100/webapps/bookstore.war
RUN rm -rf tomcat.tar.gz
EXPOSE 8080

CMD ["/opt/apache-tomcat-8.5.100/bin/catalina.sh", "run"]